import { Inter, Ubuntu } from "next/font/google";
import "./globals.css"; 
import Header from "@/components/common/header";
import SiteEssentialLinks from "@/components/common/siteEssentialLinks";
import SiteEsentialFeatures from "@/components/common/siteEsentialFeatures";
import Footer from "@/components/common/footer";
import BackToTop from "@/components/common/backToTop";

const inter = Ubuntu({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ['300','400','500','700'],
  display: "swap",
});

export const metadata = {
  title: "Animales Pet Shop",
  keywords: "Petly,Best Ecommerce Portal for Your Pets",
  description: "Generated by Petly",
};

export default async function RootLayout({ children }) {
 
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width, minimum-scale=1.0, initial-scale=1, shrink-to-fit=no"
        />
        <link rel="icon" type="image/x-icon" href={``}></link>
      </head>
      <body className={` ${inter.className}`}>
          <Header />
          {children}
          <SiteEssentialLinks />
          <SiteEsentialFeatures />
          <Footer />
          <BackToTop /> 
      </body>
    </html>
  );
}
